"use client";

import { FormEvent, useEffect, useState } from "react";
import { Building2, Save } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

export default function BusinessSettingsClient() {
  const supabase = createClient();
  const [orgId, setOrgId] = useState("");
  const [form, setForm] = useState({ name:"", legal_name:"", tax_id:"", phone:"", email:"", address:"", city:"", country:"CO", currency:"COP" });
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  useEffect(()=>{(async()=>{try{setLoading(true);const {data:{user}}=await supabase.auth.getUser();if(!user) throw new Error("No hay sesión activa.");const {data:m}=await supabase.from("organization_members").select("organization_id").eq("user_id",user.id).maybeSingle();if(!m?.organization_id) throw new Error("No tienes organización asignada.");setOrgId(m.organization_id);const {data:o,error:e}=await supabase.from("organizations").select("name,legal_name,tax_id,phone,email,address,city,country,currency").eq("id",m.organization_id).single();if(e)throw e;if(o)setForm({name:o.name??"",legal_name:o.legal_name??"",tax_id:o.tax_id??"",phone:o.phone??"",email:o.email??"",address:o.address??"",city:o.city??"",country:o.country??"CO",currency:o.currency??"COP"});}catch(e){setError(e instanceof Error?e.message:"No fue posible cargar la configuración.");}finally{setLoading(false);}})()},[]);
  async function submit(e:FormEvent){e.preventDefault();try{setSaving(true);setError("");setMessage("");const {error:e2}=await supabase.from("organizations").update({...form,name:form.name.trim(),legal_name:form.legal_name.trim()||null,tax_id:form.tax_id.trim()||null,phone:form.phone.trim()||null,email:form.email.trim()||null,address:form.address.trim()||null,city:form.city.trim()||null}).eq("id",orgId);if(e2)throw e2;setMessage("Configuración guardada correctamente.");}catch(e){setError(e instanceof Error?e.message:"No fue posible guardar.");}finally{setSaving(false)}}
  if(loading)return <div className="card">Cargando configuración...</div>;
  return <div className="card"><div className="section-head"><div><h2>Configuración del taller</h2><div className="muted">Datos que se usarán en facturación y documentos.</div></div><Building2 size={16}/></div>{message&&<div className="card" style={{marginBottom:12}}>{message}</div>}{error&&<div className="card" style={{marginBottom:12,color:"#a52222"}}>{error}</div>}<form className="form-grid" onSubmit={submit}><div className="field"><label>Nombre comercial</label><input value={form.name} required onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="field"><label>Razón social</label><input value={form.legal_name} onChange={e=>setForm({...form,legal_name:e.target.value})}/></div><div className="field"><label>NIT / Identificación</label><input value={form.tax_id} onChange={e=>setForm({...form,tax_id:e.target.value})}/></div><div className="field"><label>Teléfono</label><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><div className="field"><label>Correo</label><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div className="field"><label>Ciudad</label><input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></div><div className="field" style={{gridColumn:"1 / -1"}}><label>Dirección</label><input value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></div><div style={{display:"flex",justifyContent:"flex-end",gridColumn:"1 / -1"}}><button className="btn btn-primary" disabled={saving}><Save size={14}/>{saving?"Guardando...":"Guardar configuración"}</button></div></form></div>;
}
