"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Bike, ClipboardList, Users, WalletCards, RefreshCcw } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

export default function DashboardRealClient(){
 const supabase=useMemo(()=>createClient(),[]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [metrics,setMetrics]=useState({customers:0,motorcycles:0,orders:0,openOrders:0,total:0});
 async function load(){try{setLoading(true);setError("");const {data:{user},error:ue}=await supabase.auth.getUser();if(ue)throw ue;if(!user)throw new Error("No existe una sesión activa.");const {data:m,error:me}=await supabase.from("organization_members").select("organization_id").eq("user_id",user.id).maybeSingle();if(me)throw me;if(!m?.organization_id)throw new Error("El usuario autenticado no tiene una organización asignada.");const o=m.organization_id;const [c,mo,so]=await Promise.all([supabase.from("customers").select("id",{count:"exact",head:true}).eq("organization_id",o).eq("active",true),supabase.from("motorcycles").select("id",{count:"exact",head:true}).eq("organization_id",o).eq("active",true),supabase.from("service_orders").select("status,total").eq("organization_id",o)]);if(c.error)throw c.error;if(mo.error)throw mo.error;if(so.error)throw so.error;const rows=so.data??[];setMetrics({customers:c.count??0,motorcycles:mo.count??0,orders:rows.length,openOrders:rows.filter(r=>!['delivered','cancelled'].includes(r.status)).length,total:rows.reduce((s,r)=>s+Number(r.total||0),0)});}catch(e){setError(e instanceof Error?e.message:"No fue posible cargar el dashboard.");}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 return <><div className="section-head"><div><div className="eyebrow">Resumen operativo</div><h1 className="page-title">Dashboard</h1><p className="page-subtitle">Indicadores en tiempo real de clientes, motocicletas y órdenes del taller.</p></div><button className="btn btn-ghost" onClick={load}><RefreshCcw size={14}/>Actualizar</button></div>{error&&<div style={{marginBottom:14,padding:"10px 12px",borderRadius:8,background:"#fff0f0",color:"#a52222",fontSize:12}}>{error}</div>}<div className="grid grid-4"><Metric icon={<Users size={17}/>} label="Clientes activos" value={loading?"…":metrics.customers.toLocaleString("es-CO")} href="/clientes"/><Metric icon={<Bike size={17}/>} label="Motocicletas activas" value={loading?"…":metrics.motorcycles.toLocaleString("es-CO")} href="/motocicletas"/><Metric icon={<ClipboardList size={17}/>} label="Órdenes" value={loading?"…":metrics.orders.toLocaleString("es-CO")} href="/ordenes"/><Metric icon={<WalletCards size={17}/>} label="Valor órdenes" value={loading?"…":`$${metrics.total.toLocaleString("es-CO")}`} href="/reportes"/></div><div style={{height:16}}/><div className="grid grid-2"><div className="card"><div className="section-head"><h2>Estado operativo</h2></div><div className="grid" style={{gap:12}}><div style={{display:"flex",justifyContent:"space-between"}}><span>Órdenes abiertas</span><strong>{metrics.openOrders}</strong></div><div style={{display:"flex",justifyContent:"space-between"}}><span>Órdenes cerradas</span><strong>{Math.max(0,metrics.orders-metrics.openOrders)}</strong></div><div style={{display:"flex",justifyContent:"space-between",borderTop:"1px solid #e8eceb",paddingTop:10}}><span>Total órdenes</span><strong>{metrics.orders}</strong></div></div></div><div className="card"><div className="section-head"><h2>Accesos rápidos</h2></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><Link href="/recepcion" className="btn btn-primary">Nueva recepción</Link><Link href="/ordenes" className="btn btn-ghost">Ver órdenes</Link><Link href="/clientes" className="btn btn-ghost">Clientes</Link><Link href="/inventario" className="btn btn-ghost">Inventario</Link></div></div></div></>;
}
function Metric({icon,label,value,href}:{icon:React.ReactNode;label:string;value:string;href:string}){return <Link href={href} className="card" style={{textDecoration:"none",color:"inherit"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span className="muted" style={{fontSize:11}}>{label}</span>{icon}</div><strong style={{display:"block",fontSize:24,marginTop:8}}>{value}</strong></Link>}
