"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {ArrowLeft,FileText,Printer} from "lucide-react";
import {createClient} from "@/lib/supabase/client";
import {money} from "@/lib/utils";

type Invoice={id:string;invoice_number:string;service_order_id:string|null;customer_id:string|null;subtotal:number|string;tax:number|string;total:number|string;paid:number|string;status:string;issued_at:string;due_at:string|null};
type Customer={full_name:string;phone:string|null;email:string|null};
export default function InvoiceDetailClient({invoiceId}:{invoiceId:string}){const supabase=createClient();const [invoice,setInvoice]=useState<Invoice|null>(null);const [customer,setCustomer]=useState<Customer|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");useEffect(()=>{(async()=>{try{const {data:i,error:e}=await supabase.from("invoices").select("*").eq("id",invoiceId).single();if(e)throw e;setInvoice(i);if(i?.customer_id){const {data:c}=await supabase.from("customers").select("full_name,phone,email").eq("id",i.customer_id).maybeSingle();setCustomer(c)}}catch(e){setError(e instanceof Error?e.message:"No fue posible cargar la factura.")}finally{setLoading(false)}})()},[invoiceId]);if(loading)return <div className="card">Cargando factura...</div>;if(error||!invoice)return <div className="card">{error||"Factura no encontrada."}</div>;const saldo=Math.max(0,Number(invoice.total)-Number(invoice.paid));return <><Link href="/facturacion" className="btn btn-ghost"><ArrowLeft size={14}/>Volver</Link><div style={{height:12}}/><div className="card"><div className="section-head"><div><div className="eyebrow">Factura</div><h1 className="page-title">{invoice.invoice_number}</h1><div className="muted">Emitida {new Date(invoice.issued_at).toLocaleString("es-CO")}</div></div><div style={{display:"flex",gap:8,alignItems:"center"}}><Link href={`/facturacion/${invoice.id}/pdf`} target="_blank" className="btn btn-primary"><Printer size={14}/>PDF / Imprimir</Link><FileText size={18}/></div></div><div className="grid grid-2"><div><div className="muted">Cliente</div><strong>{customer?.full_name||"Cliente no registrado"}</strong>{customer?.phone&&<div className="muted">{customer.phone}</div>}{customer?.email&&<div className="muted">{customer.email}</div>}</div><div><div className="muted">Orden de servicio</div><strong>{invoice.service_order_id||"Venta directa"}</strong></div></div><div style={{height:16}}/><div style={{fontSize:13}}><div style={{display:"flex",justifyContent:"space-between",padding:"6px 0"}}><span>Subtotal</span><strong>{money(Number(invoice.subtotal))}</strong></div><div style={{display:"flex",justifyContent:"space-between",padding:"6px 0"}}><span>Impuestos</span><strong>{money(Number(invoice.tax))}</strong></div><hr/><div style={{display:"flex",justifyContent:"space-between",padding:"10px 0",fontSize:18}}><strong>Total</strong><strong>{money(Number(invoice.total))}</strong></div><div style={{display:"flex",justifyContent:"space-between",padding:"6px 0"}}><span>Pagado</span><strong>{money(Number(invoice.paid))}</strong></div><div style={{display:"flex",justifyContent:"space-between",padding:"6px 0"}}><span>Saldo</span><strong>{money(saldo)}</strong></div></div></div></>}
