"use client";

import { useEffect, useMemo, useState } from "react";
import { BarChart3, CalendarDays, RefreshCcw } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

export default function ReportsClient(){
 const supabase=useMemo(()=>createClient(),[]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [orders,setOrders]=useState<any[]>([]);const [from,setFrom]=useState("");const [to,setTo]=useState("");
 async function org(){const {data:{user},error:e}=await supabase.auth.getUser();if(e)throw e;if(!user)throw new Error("No existe una sesión activa.");const {data,error}=await supabase.from("organization_members").select("organization_id").eq("user_id",user.id).maybeSingle();if(error)throw error;if(!data?.organization_id)throw new Error("El usuario autenticado no tiene una organización asignada.");return data.organization_id as string;}
 async function load(){try{setLoading(true);setError("");const o=await org();let q=supabase.from("service_orders").select("id,order_number,status,total,received_at,delivered_at").eq("organization_id",o).order("received_at",{ascending:false});if(from)q=q.gte("received_at",`${from}T00:00:00`);if(to)q=q.lte("received_at",`${to}T23:59:59`);const {data,error}=await q;if(error)throw error;setOrders(data??[]);}catch(e){setError(e instanceof Error?e.message:"No fue posible cargar reportes.");}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);const metrics=useMemo(()=>{const total=orders.reduce((s,o)=>s+Number(o.total||0),0);const delivered=orders.filter(o=>o.status==="delivered").length;const open=orders.filter(o=>!['delivered','cancelled'].includes(o.status)).length;return {count:orders.length,total,delivered,open};},[orders]);
 return <><div className="section-head"><div><div className="eyebrow">Indicadores operativos</div><h1 className="page-title">Reportes</h1><p className="page-subtitle">Resumen de órdenes, ventas registradas y estado operativo.</p></div><button className="btn btn-ghost" onClick={load}><RefreshCcw size={14}/>Actualizar</button></div>{error&&<div style={{marginBottom:14,padding:"10px 12px",borderRadius:8,background:"#fff0f0",color:"#a52222",fontSize:12}}>{error}</div>}<div className="card" style={{marginBottom:16}}><div className="form-grid"><div className="field"><label>Desde</label><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></div><div className="field"><label>Hasta</label><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></div></div><button className="btn btn-primary" onClick={load}><CalendarDays size={14}/>Aplicar filtros</button></div><div className="grid grid-4"><Metric label="Órdenes" value={metrics.count.toLocaleString("es-CO")}/><Metric label="Total órdenes" value={`$${metrics.total.toLocaleString("es-CO")}`}/><Metric label="Entregadas" value={metrics.delivered.toLocaleString("es-CO")}/><Metric label="Pendientes" value={metrics.open.toLocaleString("es-CO")}/></div><div style={{height:16}}/><div className="card"><div className="section-head"><h2>Órdenes recientes</h2><BarChart3 size={16}/></div>{loading?<div className="empty">Cargando...</div>:orders.length===0?<div className="empty">No hay datos para el periodo seleccionado.</div>:<div className="table-wrap"><table className="table"><thead><tr><th>Orden</th><th>Estado</th><th>Ingreso</th><th>Entrega</th><th>Total</th></tr></thead><tbody>{orders.slice(0,25).map(o=><tr key={o.id}><td><strong>#{o.order_number}</strong></td><td>{o.status}</td><td>{new Date(o.received_at).toLocaleDateString("es-CO")}</td><td>{o.delivered_at?new Date(o.delivered_at).toLocaleDateString("es-CO"):"—"}</td><td>${Number(o.total||0).toLocaleString("es-CO")}</td></tr>)}</tbody></table></div>}</div></>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="card"><div className="muted" style={{fontSize:11}}>{label}</div><strong style={{display:"block",fontSize:22,marginTop:6}}>{value}</strong></div>}
